""" vundle
source ~/.vimrc.bundle
""
"""color
source ~/.vimrc.color
""
""" statusline
source ~/.vimrc.statusline
""
""
""" basic
""" ここにたくさん書きすぎ
source ~/.vimrc.basic
""
"""neocomplcache
"source ~/.vimrc.neocomplcache
""
""" file encoding
"source ~/.vimrc.fileencoding
""
""" comment
source ~/.vimrc.comment
""

"バッファのカレントに異同
":cd %:h
"" slimv
"let g:slimv_swank_cmd = '! xterm -e clisp -i /usr/share/common-lisp/source/slime/start-swank.lisp &'

